/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certification {
  'date' : string,
  'name' : string,
  'credentialId' : string,
  'organization' : string,
  'credentialUrl' : string,
}
export interface Education {
  'gpa' : string,
  'endDate' : string,
  'institution' : string,
  'degree' : string,
  'honors' : string,
  'fieldOfStudy' : string,
  'startDate' : string,
}
export interface Language { 'name' : string, 'proficiency' : string }
export interface PersonalInfo {
  'linkedIn' : string,
  'email' : string,
  'website' : string,
  'address' : string,
  'phone' : string,
  'lastName' : string,
  'github' : string,
  'firstName' : string,
}
export interface Project {
  'name' : string,
  'description' : string,
  'website' : string,
  'technologies' : Array<string>,
  'github' : string,
}
export interface Resume {
  'projects' : Array<Project>,
  'education' : Array<Education>,
  'workExperience' : Array<WorkExperience>,
  'languages' : Array<Language>,
  'summary' : string,
  'certifications' : Array<Certification>,
  'personalInfo' : PersonalInfo,
  'skills' : Array<Skill>,
}
export interface Skill {
  'name' : string,
  'proficiency' : string,
  'certified' : boolean,
}
export interface WorkExperience {
  'endDate' : string,
  'description' : string,
  'company' : string,
  'jobTitle' : string,
  'location' : string,
  'startDate' : string,
}
export interface _SERVICE {
  'getAllResumes' : ActorMethod<[], Array<Resume>>,
  'getMyResume' : ActorMethod<[], Resume>,
  'hasResume' : ActorMethod<[], boolean>,
  'saveResume' : ActorMethod<[Resume], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];