/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'technologies' : IDL.Vec(IDL.Text),
  'github' : IDL.Text,
});
export const Education = IDL.Record({
  'gpa' : IDL.Text,
  'endDate' : IDL.Text,
  'institution' : IDL.Text,
  'degree' : IDL.Text,
  'honors' : IDL.Text,
  'fieldOfStudy' : IDL.Text,
  'startDate' : IDL.Text,
});
export const WorkExperience = IDL.Record({
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Language = IDL.Record({
  'name' : IDL.Text,
  'proficiency' : IDL.Text,
});
export const Certification = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'credentialId' : IDL.Text,
  'organization' : IDL.Text,
  'credentialUrl' : IDL.Text,
});
export const PersonalInfo = IDL.Record({
  'linkedIn' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'github' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Skill = IDL.Record({
  'name' : IDL.Text,
  'proficiency' : IDL.Text,
  'certified' : IDL.Bool,
});
export const Resume = IDL.Record({
  'projects' : IDL.Vec(Project),
  'education' : IDL.Vec(Education),
  'workExperience' : IDL.Vec(WorkExperience),
  'languages' : IDL.Vec(Language),
  'summary' : IDL.Text,
  'certifications' : IDL.Vec(Certification),
  'personalInfo' : PersonalInfo,
  'skills' : IDL.Vec(Skill),
});

export const idlService = IDL.Service({
  'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getMyResume' : IDL.Func([], [Resume], ['query']),
  'hasResume' : IDL.Func([], [IDL.Bool], ['query']),
  'saveResume' : IDL.Func([Resume], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'technologies' : IDL.Vec(IDL.Text),
    'github' : IDL.Text,
  });
  const Education = IDL.Record({
    'gpa' : IDL.Text,
    'endDate' : IDL.Text,
    'institution' : IDL.Text,
    'degree' : IDL.Text,
    'honors' : IDL.Text,
    'fieldOfStudy' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const WorkExperience = IDL.Record({
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Language = IDL.Record({ 'name' : IDL.Text, 'proficiency' : IDL.Text });
  const Certification = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'credentialId' : IDL.Text,
    'organization' : IDL.Text,
    'credentialUrl' : IDL.Text,
  });
  const PersonalInfo = IDL.Record({
    'linkedIn' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'github' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Skill = IDL.Record({
    'name' : IDL.Text,
    'proficiency' : IDL.Text,
    'certified' : IDL.Bool,
  });
  const Resume = IDL.Record({
    'projects' : IDL.Vec(Project),
    'education' : IDL.Vec(Education),
    'workExperience' : IDL.Vec(WorkExperience),
    'languages' : IDL.Vec(Language),
    'summary' : IDL.Text,
    'certifications' : IDL.Vec(Certification),
    'personalInfo' : PersonalInfo,
    'skills' : IDL.Vec(Skill),
  });
  
  return IDL.Service({
    'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getMyResume' : IDL.Func([], [Resume], ['query']),
    'hasResume' : IDL.Func([], [IDL.Bool], ['query']),
    'saveResume' : IDL.Func([Resume], [], []),
  });
};

export const init = ({ IDL }) => { return []; };